name: Build bulk_send-WebApp in Shared (Push Tag)

on:
  push:
    tags:
      - '*.*.*-develop'
      - '*.*.*-staging'
      - '*.*.*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_latest: ${{ steps.setup_outputs.outputs.image_latest }}
      image_tag_latest: ${{ steps.setup_outputs.outputs.image_tag_latest }}
      extra_build_args: ${{ steps.extra_build_args.outputs.BUILD_ENV_ARGS }}
      manifests_environment: ${{ steps.setup_outputs.outputs.MANIFESTS_ENVIRONMENT }}
    steps:
      - name: Set outputs
        id: setup_outputs
        run: |
          TAG="$( echo "${GITHUB_REF}" | cut -d'/' -f3 )"
          if [[ "${TAG}" =~ ^.*.*-develop ]]; then
            echo "Found environment: DEVELOP - ${TAG}"
            echo "MANIFESTS_ENVIRONMENT=develop" >> "${GITHUB_OUTPUT}"
          elif [[ "${TAG}" =~ ^.*.*-staging ]]; then
            echo "Found environment: STAGING - ${TAG}"
            echo "MANIFESTS_ENVIRONMENT=staging" >> "${GITHUB_OUTPUT}"
          elif [[ "${TAG}" =~ ^.*.* ]]; then
            echo "No environment found, assuming: PRODUCTION - ${TAG}"
            echo "MANIFESTS_ENVIRONMENT=production" >> "${GITHUB_OUTPUT}"
          else
            echo 'Not a valid tag. Skipping...'
            exit 1
          fi
          echo "image_latest=${{ secrets.REGISTRY_ECR }}/bulk-send:latest-${MANIFESTS_ENVIRONMENT}" >> "${GITHUB_OUTPUT}"
          echo "image_tag_latest=latest-${MANIFESTS_ENVIRONMENT}" >> "${GITHUB_OUTPUT}"
      
      - name: Download webapp secret
        uses: actions/checkout@v4
        with:
          ref: main
          repository: "weni-ai/webapp-secret"
          token: "${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}"
          path: ./webapp-secret/ 

      - name: Set variables
        id: extra_build_args
        run: |
          {
            echo "BUILD_ENV_ARGS<<EOF"
            cat "webapp-secret/bulk_send/${{ steps.setup_outputs.outputs.MANIFESTS_ENVIRONMENT }}/env" || exit 1
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"
          rm -rf webapp-secret

  call-workflow:
    uses: weni-ai/actions-workflows/.github/workflows/reusable-workflow.yaml@main
    needs:
      - setup
    with:
      image_repository: bulk-send
      image_tags: |
        type=ref,event=tag
        type=raw,${{ needs.setup.outputs.image_tag_latest }}
      image_tag_prefix: "webapp-"
      dockerfile: "docker/Dockerfile"
      build_args: |
        OLD_IMAGE=869898323958.dkr.ecr.us-east-1.amazonaws.com/bulk-send:webapp-${{ needs.setup.outputs.image_tag_latest }}
        ${{ needs.setup.outputs.extra_build_args }}
      target_repository: weni-ai/kubernetes-manifests-platform
      target_repository_branch: main
      target_application: bulk-send
      target_patch_file: deployment.json
    secrets: inherit
